# Generated by Django 3.2.15 on 2022-09-27 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cursos', '0002_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='nome',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='NotasAulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(choices=[('p', 'Péssimo'), ('r', 'Ruim'), ('re', 'Regular'), ('b', 'bom'), ('o', 'Ótimo')], max_length=50)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cursos.aulas')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
